---
- name: Install Docker and Run Image
  hosts: machines
  become: true

  vars:
    docker_image_sha: "sha256:367a6ee6048d4187fbaef258a528b64781e909819e65dc86c2834d92ff9b7db3"
    docker_image_name: "barhaim10/the-last-jenkins-exercise"
    container_name: "jenkins-demo-container"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull image by digest
      command: docker pull {{ docker_image_name }}@{{ docker_image_sha }}

    - name: Run container from image with python app.py
      command: docker run -d --name {{ container_name }} {{ docker_image_name }}@{{ docker_image_sha }} python app.py
